@Jargar.SchemeServe.Connector.Api_HostAddress = http://localhost:5122

GET {{Jargar.SchemeServe.Connector.Api_HostAddress}}/api/connectors
Accept: application/json

###

GET {{Jargar.SchemeServe.Connector.Api_HostAddress}}/api/connectors/1-10000227676

Accept: application/json

###
